<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon />
    <RootNamespace>ShopeeVideoUploader</RootNamespace>
    <AssemblyName>ShopeeVideoUploader</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <DefaultItemExcludes>$(DefaultItemExcludes);spreadsheet-work\**;node_modules\**;Installer\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AdvancedSharpAdbClient" Version="3.6.16" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.8" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="ReaLTaiizor" Version="*" />
    <PackageReference Include="MiniExcel" Version="*" />
    <PackageReference Include="Newtonsoft.Json" Version="13.*" />
  </ItemGroup>

  <ItemGroup>
    <None Update="scrcpy\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
